services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.4
    container_name: jellyfin
    restart: unless-stopped
    #network_mode: 'host'
    networks:
      - proxy
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/data/media:/media
    environment:
      TZ: America/Sao_Paulo
    labels:
      - 'traefik.enable=true'
      #- 'traefik.http.routers.jellyfin.entryPoints=web'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.hlspace.org`)'

      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true

volumes:
  jellyfin_config:
  jellyfin_cache:
