version: '3.8'

services:
  borg-ui:
    image: ainullcode/borg-ui:latest
    container_name: borg-web-ui
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - borg_data:/data
      - borg_cache:/home/borg/.cache/borg
      # Mount directories you want to backup (REPLACE with your actual paths)
      - /home/luiz:/local/home:rw
      - /mnt/data/backup:/backup:rw       # Replace with your directory path

      # Backup Jellyfin
      - jellyfin_jellyfin_config:/local/jellyfin:rw
    environment:
      - TZ=America/Sao_Paulo  # Set your timezone
      - PUID=1000
      - PGID=1000
    labels:
      - 'traefik.enable=true'
      #- 'traefik.http.routers.borg.entryPoints=web'
      - 'traefik.http.routers.borg.rule=Host(`borg.hlspace.org`)'
      - "traefik.http.routers.borg.entrypoints=websecure"
      - "traefik.http.routers.borg.tls.certresolver=letsencrypt"
      - "traefik.http.services.borg.loadbalancer.server.port=8081"

networks:
  proxy:
    external: true

volumes:
  borg_data:
  borg_cache:
  jellyfin_jellyfin_config:
    external: true