name: OpenTofu Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0

      - run: tofu init

      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: tofu plan -out=tfplan

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan-artifact
          path: tfplan