name: OpenTofu CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0 # Specify your desired OpenTofu version

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Plan
        run: tofu plan -out=tfplan # Stores the plan for later use

      - name: Upload OpenTofu Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-artifact
          path: tfplan

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: plan # Ensures plan job runs successfully before apply
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.0

      - name: Download OpenTofu Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-artifact

      - name: OpenTofu Apply
        run: tofu apply -auto-approve tfplan # Applies the stored plan